À: "A"
Á: "A"
Â: "A"
Ã: "A"
Ä: "A"
Å: "A"
Æ: "AE"
Ç: "C"
È: "E"
É: "E"
Ê: "E"
Ë: "E"
Ì: "I"
Í: "I"
Î: "I"
Ï: "I"
Ð: "D"
Ñ: "N"
Ò: "O"
Ó: "O"
Ô: "O"
Õ: "O"
Ö: "O"
×: "x"
Ø: "O"
Ù: "U"
Ú: "U"
Û: "U"
Ü: "U"
Ý: "Y"
Þ: "Th"
ß: "ss"
à: "a"
á: "a"
â: "a"
ã: "a"
ä: "a"
å: "a"
æ: "ae"
ç: "c"
è: "e"
é: "e"
ê: "e"
ë: "e"
ì: "i"
í: "i"
î: "i"
ï: "i"
ð: "d"
ñ: "n"
ò: "o"
ó: "o"
ô: "o"
õ: "o"
ö: "o"
ø: "o"
ù: "u"
ú: "u"
û: "u"
ü: "u"
ý: "y"
þ: "th"
ÿ: "y"
Ā: "A"
ā: "a"
Ă: "A"
ă: "a"
Ą: "A"
ą: "a"
Ć: "C"
ć: "c"
Ĉ: "C"
ĉ: "c"
Ċ: "C"
ċ: "c"
Č: "C"
č: "c"
Ď: "D"
ď: "d"
Đ: "D"
đ: "d"
Ē: "E"
ē: "e"
Ĕ: "E"
ĕ: "e"
Ė: "E"
ė: "e"
Ę: "E"
ę: "e"
Ě: "E"
ě: "e"
Ĝ: "G"
ĝ: "g"
Ğ: "G"
ğ: "g"
Ġ: "G"
ġ: "g"
Ģ: "G"
ģ: "g"
Ĥ: "H"
ĥ: "h"
Ħ: "H"
ħ: "h"
Ĩ: "I"
ĩ: "i"
Ī: "I"
ī: "i"
Ĭ: "I"
ĭ: "i"
Į: "I"
į: "i"
İ: "I"
ı: "i"
Ĳ: "IJ"
ĳ: "ij"
Ĵ: "J"
ĵ: "j"
Ķ: "K"
ķ: "k"
ĸ: "k"
Ĺ: "L"
ĺ: "l"
Ļ: "L"
ļ: "l"
Ľ: "L"
ľ: "l"
Ŀ: "L"
ŀ: "l"
Ł: "L"
ł: "l"
Ń: "N"
ń: "n"
Ņ: "N"
ņ: "n"
Ň: "N"
ň: "n"
ŉ: "'n"
Ŋ: "NG"
ŋ: "ng"
Ō: "O"
ō: "o"
Ŏ: "O"
ŏ: "o"
Ő: "O"
ő: "o"
Œ: "OE"
œ: "oe"
Ŕ: "R"
ŕ: "r"
Ŗ: "R"
ŗ: "r"
Ř: "R"
ř: "r"
Ś: "S"
ś: "s"
Ŝ: "S"
ŝ: "s"
Ş: "S"
ş: "s"
Š: "S"
š: "s"
Ţ: "T"
ţ: "t"
Ť: "T"
ť: "t"
Ŧ: "T"
ŧ: "t"
Ũ: "U"
ũ: "u"
Ū: "U"
ū: "u"
Ŭ: "U"
ŭ: "u"
Ů: "U"
ů: "u"
Ű: "U"
ű: "u"
Ų: "U"
ų: "u"
Ŵ: "W"
ŵ: "w"
Ŷ: "Y"
ŷ: "y"
Ÿ: "Y"
Ź: "Z"
ź: "z"
Ż: "Z"
ż: "z"
Ž: "Z"
ž: "z"
# # az.yml
# c: "j"
# ç: "ch"
# ə: "e"
# ğ: "gh"
# x: "kh"
# ı: "i"
# j: "zh"
# q: "g"
# ş: "sh"
# ü: "u"
# C: "J"
# Ç: "Ch"
# Ə: "E"
# Ğ: "Gh"
# X: "Kh"
# İ: "I"
# J: "Zh"
# Q: "G"
# Ş: "Sh"
# Ü: "U"
# # bg.yml
# а: "a"
# А: "A"
# б: "b"
# Б: "B"
# в: "v"
# В: "V"
# г: "g"
# Г: "G"
# д: "d"
# Д: "D"
# е: "e"
# Е: "E"
# ж: "zh"
# Ж: "Zh"
# з: "z"
# З: "Z"
# и: "i"
# И: "I"
# й: "y"
# Й: "Y"
# к: "k"
# К: "K"
# л: "l"
# Л: "L"
# м: "m"
# М: "M"
# н: "n"
# Н: "N"
# о: "o"
# О: "O"
# п: "p"
# П: "P"
# р: "r"
# Р: "R"
# с: "s"
# С: "S"
# т: "t"
# Т: "T"
# у: "u"
# У: "U"
# ф: "f"
# Ф: "F"
# х: "h"
# Х: "H"
# ц: "ts"
# Ц: "Ts"
# ч: "ch"
# Ч: "Ch"
# ш: "sh"
# Ш: "Sh"
# щ: "sht"
# Щ: "Sht"
# ъ: "a"
# Ъ: "A"
# ь: "y"
# Ь: "Y"
# ю: "yu"
# Ю: "Yu"
# я: "ya"
# Я: "Ya"
# # ca.yml
# à: "a"
# á: "a"
# ç: "c"
# é: "e"
# è: "e"
# ë: "e"
# í: "i"
# ï: "i"
# ó: "o"
# ò: "o"
# ú: "u"
# ü: "u"
# À: "A"
# Á: "A"
# Ç: "C"
# É: "E"
# È: "E"
# Ë: "E"
# Í: "I"
# Ï: "I"
# Ó: "O"
# Ò: "O"
# Ú: "U"
# Ü: "U"
# # de.yml
# ä: "ae"
# é: "e"
# ü: "ue"
# ö: "oe"
# Ä: "Ae"
# Ü: "Ue"
# Ö: "Oe"
# ß: "ss"
# # el.yml
# α: "a"
# ά: "a"
# Α: "a"
# Ά: "a"
# β: "v"
# Β: "v"
# γ: "g"
# Γ: "g"
# δ: "d"
# Δ: "d"
# ε: "e"
# έ: "e"
# Ε: "e"
# Έ: "e"
# ζ: "z"
# Ζ: "z"
# η: "h"
# ή: "h"
# Η: "h"
# Ή: "h"
# θ: "th"
# Θ: "th"
# ι: "I"
# ί: "I"
# Ι: "I"
# Ί: "I"
# κ: "k"
# Κ: "k"
# λ: "l"
# Λ: "l"
# μ: "m"
# Μ: "m"
# ν: "n"
# Ν: "n"
# ξ: "x"
# Ξ: "x"
# ο: "o"
# Ο: "o"
# ό: "o"
# Ό: "o"
# π: "p"
# Π: "p"
# ρ: "r"
# Ρ: "r"
# σ: "s"
# Σ: "s"
# ς: "s"
# τ: "t"
# Τ: "t"
# υ: "y"
# ύ: "y"
# Υ: "y"
# Ύ: "y"
# φ: "f"
# Φ: "f"
# χ: "ch"
# Χ: "ch"
# ψ: "ps"
# Ψ: "ps"
# ω: "w"
# ώ: "w"
# Ώ: "w"
# Ω: "w"
# αι: "ai"
# αί: "ai"
# άι: "ai"
# ΑΙ: "ai"
# ΑΊ: "ai"
# ΆΙ: "ai"
# οι: "oi"
# οί: "oi"
# όι: "oi"
# ΟΙ: "oi"
# ΟΊ: "oi"
# ΌΙ: "oi"
# ει: "ei"
# έι: "ei"
# ΕΙ: "ei"
# ΕΊ: "ei"
# ΈΙ: "ei"
# ου: "u"
# όυ: "u"
# ού: "u"
# ΟΥ: "u"
# ΌΥ: "u"
# ΟΎ: "u"
# αυ: "av"
# αύ: "av"
# άυ: "av"
# ΆΥ: "av"
# ΑΎ: "av"
# ΑΥ: "av"
# ευ: "ev"
# εύ: "ev"
# έυ: "ev"
# ΕΥ: "ev"
# ΕΎ: "ev"
# ΈΥ: "ev"
# ϊ: "i"
# ϋ: "i"
# # es.yml
# á: "a"
# é: "e"
# í: "i"
# ó: "o"
# ú: "u"
# ü: "u"
# ñ: "n"
# Á: "A"
# É: "E"
# Í: "I"
# Ó: "O"
# Ú: "U"
# Ü: "U"
# Ñ: "N"
# # fa.yml
# 'آ': 'a'
# 'ا': 'a'
# 'ب': 'b'
# 'پ': 'p'
# 'ت': 't'
# 'ث': 's'
# 'ج': 'g'
# 'چ': 'ch'
# 'ح': 'h'
# 'خ': 'kh'
# 'د': 'd'
# 'ذ': 'z'
# 'ر': 'r'
# 'ز': 'z'
# 'ژ': 'j'
# 'س': 's'
# 'ش': 'sh'
# 'ص': 's'
# 'ض': 'z'
# 'ط': 't'
# 'ظ': 'z'
# 'ع': 'a'
# 'غ': 'q'
# 'ف': 'f'
# 'ق': 'q'
# 'ک': 'k'
# 'گ': 'gh'
# 'ل': 'l'
# 'م': 'm'
# 'ن': 'n'
# 'و': 'v'
# 'ه': 'h'
# 'ی': 'i'
# '۰': '0'
# '۱': '1'
# '۲': '2'
# '۳': '3'
# '۴': '4'
# '۵': '5'
# '۶': '6'
# '۷': '7'
# '۸': '8'
# '۹': '9'
# # fr.yml
# à: "a"
# â: "a"
# æ: "ae"
# ç: "c"
# é: "e"
# è: "e"
# ê: "e"
# ë: "e"
# î: "i"
# ï: "i"
# ô: "o"
# œ: "oe"
# ù: "u"
# û: "u"
# ü: "u"
# ÿ: "y"
# À: "A"
# Â: "A"
# Æ: "Ae"
# Ç: "C"
# É: "E"
# È: "E"
# Ê: "E"
# Ë: "E"
# Î: "I"
# Ï: "I"
# Ô: "O"
# Œ: "Oe"
# Ù: "U"
# Û: "U"
# Ü: "U"
# Ÿ: "Y"
# # hu.yml
# á: "a"
# é: "e"
# í: "i"
# ó: "o"
# ö: "o"
# ő: "o"
# ú: "u"
# ü: "u"
# ű: "u"
# Á: "A"
# É: "E"
# Í: "I"
# Ó: "O"
# Ö: "O"
# Ő: "O"
# Ú: "U"
# Ü: "U"
# Ű: "U"
# # oc.yml
# à: "a"
# á: "a"
# ç: "c"
# é: "e"
# è: "e"
# ë: "e"
# í: "i"
# ï: "i"
# ó: "o"
# ò: "o"
# ú: "u"
# ü: "u"
# À: "A"
# Á: "A"
# Ç: "C"
# É: "E"
# È: "E"
# Ë: "E"
# Í: "I"
# Ï: "I"
# Ó: "O"
# Ò: "O"
# Ú: "U"
# Ü: "U"
# # pl.yml
# ą: "a"
# ć: "c"
# ę: "e"
# ł: "l"
# ń: "n"
# ó: "o"
# ś: "s"
# ź: "z"
# ż: "z"
# Ą: "A"
# Ć: "C"
# Ę: "E"
# Ł: "L"
# Ń: "N"
# Ó: "O"
# Ś: "S"
# Ź: "Z"
# Ż: "Z"
# # pt.yml
# á: "a"
# à: "a"
# ã: "a"
# â: "a"
# é: "e"
# ê: "e"
# í: "i"
# ó: "o"
# õ: "o"
# ú: "u"
# Á: "A"
# À: "A"
# Ã: "A"
# É: "E"
# Ê: "E"
# Í: "I"
# Ó: "O"
# Õ: "O"
# Ú: "U"
# Æ: "Ae"
# æ: "ae"
# º: "o"
# ª: "a"
# ç: "c"
# # ro.yml
# ă: "a"
# â: "a"
# î: "i"
# ș: "s"
# ț: "t"
# Ă: "A"
# Â: "A"
# Î: "I"
# Ș: "S"
# Ț: "T"
# # vi.yml
# à: "a"
# á: "a"
# ạ: "a"
# ả: "a"
# ã: "a"
# â: "a"
# ầ: "a"
# ấ: "a"
# ậ: "a"
# ẩ: "a"
# ẫ: "a"
# ă: "a"
# ằ: "a"
# ắ: "a"
# ặ: "a"
# ẳ: "a"
# ẵ: "a"
# À: "A"
# Á: "A"
# Ạ: "A"
# Ả: "A"
# Ã: "A"
# Â: "A"
# Ầ: "A"
# Ấ: "A"
# Ậ: "A"
# Ẩ: "A"
# Ẫ: "A"
# Ă: "A"
# Ằ: "A"
# Ắ: "A"
# Ặ: "A"
# Ẳ: "A"
# Ẵ: "A"
# ì: "i"
# í: "i"
# ị: "i"
# ỉ: "i"
# ĩ: "i"
# Ì: "I"
# Í: "I"
# Ị: "I"
# Ỉ: "I"
# Ĩ: "I"
# ù: "u"
# ú: "u"
# ụ: "u"
# ủ: "u"
# ũ: "u"
# ư: "u"
# ừ: "u"
# ứ: "u"
# ự: "u"
# ử: "u"
# ữ: "u"
# Ù: "U"
# Ú: "U"
# Ụ: "U"
# Ủ: "U"
# Ũ: "U"
# Ư: "U"
# Ừ: "U"
# Ứ: "U"
# Ự: "U"
# Ử: "U"
# Ữ: "U"
# è: "e"
# é: "e"
# ẹ: "e"
# ẻ: "e"
# ẽ: "e"
# ê: "e"
# ề: "e"
# ế: "e"
# ệ: "e"
# ể: "e"
# ễ: "e"
# È: "E"
# É: "E"
# Ẹ: "E"
# Ẻ: "E"
# Ẽ: "E"
# Ê: "E"
# Ề: "E"
# Ế: "E"
# Ệ: "E"
# Ể: "E"
# Ễ: "E"
# ò: "o"
# ó: "o"
# ọ: "o"
# ỏ: "o"
# õ: "o"
# ô: "o"
# ồ: "o"
# ố: "o"
# ộ: "o"
# ổ: "o"
# ỗ: "o"
# ơ: "o"
# ờ: "o"
# ớ: "o"
# ợ: "o"
# ở: "o"
# ỡ: "o"
# Ò: "O"
# Ó: "O"
# Ọ: "O"
# Ỏ: "O"
# Õ: "O"
# Ô: "O"
# Ồ: "O"
# Ố: "O"
# Ộ: "O"
# Ổ: "O"
# Ỗ: "O"
# Ơ: "O"
# Ờ: "O"
# Ớ: "O"
# Ợ: "O"
# Ở: "O"
# Ỡ: "O"
# ỳ: "y"
# ý: "y"
# ỵ: "y"
# ỷ: "y"
# ỹ: "y"
# Ỳ: "Y"
# Ý: "Y"
# Ỵ: "Y"
# Ỷ: "Y"
# Ỹ: "Y"
# đ: "d"
# Đ: "D"
