language: shell

script:
  - true

before_deploy:
  - .travis/providers/github-pages/prepare

deploy:
  - provider: pages
    token:
      # personal access token with repo and user scopes on travis-dpl-test
      secure: "Iq437TC76lD2pY5BceuaTqcyHt6Xq8dv+/Or6tkdzwMAltmraPKA6AB7MhQTtMVwqd5rSehNqbglzTcaXU4vk8TEGYxA9VDXD/9+9VWYGMHRh5Ql+huOoVPpW4tF+ZRUpAfogB77XRROvb8TjwI2uyO1byDtq/5jRl9CeQNv5sg="
    repo: travis-ci/dpl_test
    committer_from_gh: true
    local_dir: tmp/dpl_test
    keep_history: true
    verbose: true
    commit_message: |-
      commit https://github.com/%{project_name}/commit/$TRAVIS_COMMIT

      successfully built and checked by Travis CI build $TRAVIS_BUILD_NUMBER.

      see https://travis-ci.org/%{project_name}/builds/$TRAVIS_BUILD_ID for details.

after_deploy:
  - .travis/providers/github-pages/test || TRAVIS_TEST_RESULT=$?
